### ISSUE TITLE
Clean up the "duration" abstraction (tech debt?)

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quilc#11]
`build-link` in `chip-specification.lisp` has some [notion of duration](https://github.com/rigetti/quilc/blob/master/src/chip-specification.lisp#L193) but just reading the code it's not clear what it is or how it's used. Why do some of those entries use underscores where others do not? why the backticks? why the repetition?

I think this could be cleaned up by defining some duration data structure.

**Comment by stylewarning** [comment]
See also #117

**Comment by ecpeterson** [comment]
Made configurable in #210.
