### ISSUE TITLE
print-instruction-to-string utility function

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#116]
Repeatedly, as part of `print-instruction` itself and in support of error message printing, we make use of the `nil` stream functionality of `print-instruction` to extract a string from an instruction object. If there were a more direct utility wrapper for this functionality, we could incorporate all these calls (including some `mapcar` calls) into the relevant `format` string by using `~/fn-name/`. Investigate how much this cleans up the code.

**Comment by appleby** [comment]
Can this issue be closed now, or should it morph into an issue for tracking the propagation of `"~/cl-quil::instruction-fmt/"` use throughout the code?

**Comment by notmgsk** [comment]
I'm gonna close this. We can change stuff as it comes up in other PRs.
