### ISSUE TITLE
Make anonymous gates easier

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#140]
Anonymous gates are a bit of a pain. Internally, they have to be named, even if they're a junk name. The recommendation would be to allow anonymity in the `operator-description`.

**Comment by stylewarning** [comment]
(CC @ecp-rigetti)

**Comment by ecp-rigetti** [comment]
I appreciate the junk names: we’ve been using them to track the provenance of the anonymous gate, which has come in handy in debugging and which bears no expense. I’d rather the “define global counter” incantation used in the compiler’s generation of “anonymous names” get turned into something more automatic.

**Comment by ecpeterson** [comment]
As of https://github.com/rigetti/quilc/pull/143 , `build-gate` now has a cousin, `anon-gate`, which includes such a counter.

**Comment by stylewarning** [comment]
I still don't want to close this issue quite yet, because we are using gates inconsistently internally. Often, the `gate` slot of applications is being set to the matrix itself, and I'm not sure if that's 100% kosher. I would like to keep this open until those thoughts are resolved.

**Comment by ecpeterson** [comment]
It sounds like this thought is captured in #283 , where we've made the decision about what ought to be done. I'm going to close this in favor of that issue.
