### ISSUE TITLE
PARSE-QUIL vs PARSE-QUIL-STRING

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#146]
These should be named a little bit better.

**Comment by notmgsk** [comment]
`parse-quil` makes sense. Not obvious what `parse-quil-string` should be named... `parse-quil-and-transform` maybe? @stylewarning thoughts?

**Comment by stylewarning** [comment]
I’d rather make PARSE-QUIL be something more complex, like PARSE-QUIL-INTO-RAW-PROGRAM or so. Maybe the parse+transform can be the simple one PARSE-QUIL.

Justification: the transforms also do some semantic analysis, like resolving gate names and checking arity. It’s also the DWIM function, whereas the raw parsing just gives you a barebones AST representation back that’s hardly immediately useful. 

The only questionable thing this “parsing” function does is expand INCLUDEs+circuits. 

Counter thoughts? More name ideas?

**Comment by notmgsk** [comment]
That makes sense actually. How would you feel about having the applied transforms be an optional argument to the function, so I don't have to go out of my way to customize the transform pipeline?

**Comment by stylewarning** [comment]
@notmgsk I like that idea a lot
