### ISSUE TITLE
this runtime was not built with zlib support

### ISSUE THREAD

**Issue by katetsu** [rigetti/quilc#161]
when compiling `quilc`, I'm getting this error:
`this run-time was not built with zlib support
`
full error is here:
https://pastebin.com/eSbSyRkM

Thanks in advance for any hints

**Comment by notmgsk** [comment]
Hi @katetsu. My suspicion is that you have a version of SBCL that doesn't support compression (compiled without zlib support). I suggest you either compile and install SBCL from source and configure it to use zlib; or alternatively get one of the precompiled binaries from the SBCL website: http://sbcl.org/platform-table.html

If you compile from source, you should run the following commands `sh make.sh --with-fancy --with-sb-core-compression`.

**Comment by ecpeterson** [comment]
xref https://rigetti-forest.slack.com/archives/CFXEQGNDD/p1553851942000400

**Comment by stylewarning** [comment]
As a workaround, you can safely delete this line from the build script: https://github.com/rigetti/quilc/blob/master/build-app.lisp#L51

**Comment by stylewarning** [comment]
@katetsu As a workaround, you can safely delete this `:compression t` line from the build script: https://github.com/rigetti/quilc/blob/master/build-app.lisp#L51

**Comment by stylewarning** [comment]
I am going to close this issue since we now support SBCL's without core compression.
