### ISSUE TITLE
automatically test translators

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#168]
Translators seem ripe for automatic testing. Maybe DEFINE-TRANSLATOR can stash away the translator somewhere, and as a part of unit tests, we can just test them all on random qubit arguments.

Thoughts @ecpeterson ?

**Comment by ecpeterson** [comment]
Sounds like a good idea to me. We're already encouraging the use of macros, and the macro already receives as input a mungable form of the "input" gate.

Random qubit assignments is probably somewhat excessive, but also won't be hurting anybody.

**Comment by ecpeterson** [comment]
This was "done" in #210, though Mark pointed out in #368 that there's more to be done. I'm going to close this issue in favor of that one.
