### ISSUE TITLE
Add option to print complex numbers in polar form

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#171]
I spend a lot of time staring at `print`-outs of trays of complex numbers, trying to decide if some collection of them is the same as some other collection up to phase.

We already have a complex number pretty-printer and it already has a global option to enable pretty-printing of certain fractions of pi. I'd like an option to extend it to have a global option to print polar forms of complex numbers instead of Cartesian forms.

**Comment by stylewarning** [comment]
I recommend syntax like:
```
(defun polar (z)
  (format t "~A∠~A" (abs z) (phase z)))
```
where the phase is printed with nice pi fractions when enabled.
