### ISSUE TITLE
Slack link in README is broken

### ISSUE THREAD

**Issue by appleby** [rigetti/quilc#216]
The "Get Involved!" section at the bottom of the README links to https://slack.rigetti.com/, but the connection times out for me.

```
$ curl --connect-timeout 10 https://slack.rigetti.com/
curl: (28) Connection timed out after 10000 milliseconds
```

I am able to connect to https://www.rigetti.com/ without problems.

**Comment by ecpeterson** [comment]
The pyQuil documentation has a direct link to `https://rigetti-forest.slack.com`, without a `rigetti.com` redirect. Perhaps we ought to do the same.
