### ISSUE TITLE
Provide source-of-truth for `gate-matrix` on UCR applications

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#235]
The current implementation of `gate-matrix` on `UCR-application` instruction types uses `ucr-explode-instr` as its source of truth, so that compilation is always trivially correct. This should be rigidified by providing a separate definition of `gate-matrix` as a block-diagonal matrix.

**Comment by ecpeterson** [comment]
Likely to be handled in #210.

**Comment by notmgsk** [comment]
Since there is no `ucr-application` type now, is this considered closed?

**Comment by ecpeterson** [comment]
Yes, thanks!
