### ISSUE TITLE
WARNING: deeper answer than expected

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#256]
quilc is 3deep5me. But really, running the test suite gives:
```
  TEST-OPTIMAL-2Q-TEMPLATES
    Trying test template (I)                , got NIL                 back.
    Trying test template (CZ)               , got (CZ)                back.
    Trying test template (CZ CZ)            , got (CZ CZ)             back.
    Trying test template (CZ CZ CZ)         , got (CZ CZ CZ)          back.
    Trying test template (ISWAP)            , got (ISWAP)             back.
    Trying test template (ISWAP ISWAP)      , got (ISWAP ISWAP)       back.
    Trying test template (ISWAP ISWAP ISWAP), got (ISWAP ISWAP ISWAP) back.
    Trying test template (CZ ISWAP)         , got (ISWAP CZ)          back.
    Trying test template (CPHASE)           , got (CPHASE)            back.
    Trying test template (PISWAP)           , got (PISWAP)            back.
    Trying test template (ISWAP PISWAP)     , got (ISWAP ISWAP ISWAP) back.
    WARNING: deeper answer than expected
    Trying test template (CZ PISWAP)        , got (ISWAP ISWAP ISWAP) back.
    WARNING: deeper answer than expected
    Trying test template (ISWAP CPHASE)     , got (ISWAP CZ)          back.
    Trying test template (CPHASE PISWAP)    , got (ISWAP ISWAP ISWAP) back.
    WARNING: deeper answer than expected
```

Is that OK?

**Comment by stylewarning** [comment]
CC @ecpeterson

**Comment by ecpeterson** [comment]
What I believe is happening is:

1. The test suite generates (e.g.) a circuit consisting of a CZ and a PISWAP.
2. It multiplies this out into an anonymous gate.
3. It asks the approximate compiler to produce its best approximation, which that hands off to a numerical hill-climber.
4. The hill-climber gets stuck and returns an inexact circuit.
5. The parent approximate compiler routines sees that it's inexact, sees that it's told not to tolerate inexact solutions, and that _it has no mechanism for determining whether an exact solution exists_. (This is in the monodromy polytope paper, but we haven't included it.) It therefore rejects the inexact solution and does not waste time trying again. (If it did know via the monodromy polytope paper that an exact solution existed, it would try again until it found it.)
6. The approximate compiler moves on to the 3x ISWAP template, which always nails an exact solution without recourse to numerics.
7. The test whines about depth.

**Comment by ecpeterson** [comment]
As a consequence of recent restructuring (#210), this test no longer exists and so this issue is fake news.
