### ISSUE TITLE
Create package constants pi/2 and -pi/2

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#275]
These constants show up all over the code and are often written as, eg, `#.(/ pi 2)`. We should save ourselves the trouble / ugliness and define package-level constants.

(Suggested by Robert here: https://github.com/rigetti/quilc/pull/237#discussion_r290486777 .)

**Comment by appleby** [comment]
See also: https://github.com/rigetti/quilc/pull/210#discussion_r304111867

**Comment by appleby** [comment]
Closed by #411? Not sure why auto-close keyword didn't work there...
