### ISSUE TITLE
`diagonalizer-in-e-basis` suffers numerical instability

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#278]
The following Quil snippet triggers an error during compression in quilc 1.8.2-hotfix:
```
DECLARE ro BIT[2]
H 0
H 1
X 0
PHASE(-13.823007675781957) 0
X 0
PHASE(-13.823007675781957) 0
RZ(-17.592918860086126) 0
RZ(-22.61946710582502) 1
CNOT 0 1
RZ(22.61946710582502) 1
CNOT 0 1
X 0
PHASE(-1.2566370614347233) 0
X 0
PHASE(-1.2566370614347233) 0
RZ(-2.5132741228694466) 1
RZ(-2.5132741228694466) 0
CNOT 0 1
RZ(2.5132741228694466) 1
CNOT 0 1
X 0
PHASE(-6.283185307173617) 0
X 0
PHASE(-6.283185307173617) 0
RZ(-7.539822368608339) 1
RZ(-7.539822368608339) 0
CNOT 0 1
RZ(12.566370614347234) 1
CNOT 0 1
H 0
RZ(-1.2566370614278395) 0
H 0
H 1
RZ(-1.2566370614278395) 1
H 1
MEASURE 0 ro[0]
MEASURE 1 ro[1]
```
The ultimate source of the error appears to be in `diagonalizer-in-e-basis`, which attempts to group the eigenvectors emitted by `magicl:eig` into common eigenspaces. The eigenspaces in the above sequence are completely degenerate: everything ought to belong to the eigenspace of weight 1, but `d-i-e-b` sorts them into pairs of weight 1±eps, which causes some cascading failure further down the line (specifically: `find-real-spanning-set` goes off the rails).

I propose we first look into Gavin's randomized algorithm for performing this computation. If his approach only deals with instability in `find-real-spanning-set`, then that's no help here; but if it obviates us from having to sort the eigenvectors as well, then that could be a good approach. Failing that, I don't have an immediate idea for an approach to this.

**Comment by ecpeterson** [comment]
We initially suspected that the large angle values appearing in the above snippet (e.g., `-22.61946710582502`) were part of the underlying cause, but Michał has since reported that he can trigger this bug with angles constrained to [-2pi, 2pi].

**Comment by notmgsk** [comment]
@ecpeterson with today's changes:

```
CL-USER> (let* ((p "DECLARE ro BIT[2]
H 0
H 1
X 0
PHASE(-13.823007675781957) 0
X 0
PHASE(-13.823007675781957) 0
RZ(-17.592918860086126) 0
RZ(-22.61946710582502) 1
CNOT 0 1
RZ(22.61946710582502) 1
CNOT 0 1
X 0
PHASE(-1.2566370614347233) 0
X 0
PHASE(-1.2566370614347233) 0
RZ(-2.5132741228694466) 1
RZ(-2.5132741228694466) 0
CNOT 0 1
RZ(2.5132741228694466) 1
CNOT 0 1
X 0
PHASE(-6.283185307173617) 0
X 0
PHASE(-6.283185307173617) 0
RZ(-7.539822368608339) 1
RZ(-7.539822368608339) 0
CNOT 0 1
RZ(12.566370614347234) 1
CNOT 0 1
H 0
RZ(-1.2566370614278395) 0
H 0
H 1
RZ(-1.2566370614278395) 1
H 1
MEASURE 0 ro[0]
MEASURE 1 ro[1]")
                (pp (quil:parse-quil p)))
           (quil::print-parsed-program (quil:compiler-hook pp (quil::build-nq-fully-connected-chip 3))))
DECLARE ro BIT[2]

RZ(2.3812748610449956) 1                # Entering rewiring: #(0 1 2)
RX(pi/2) 1
RZ(0.440570547736455) 1
RX(-pi/2) 1
RZ(-0.7603177924704826) 1
MEASURE 1 ro[1]
RZ(-1.9527009134848787) 0
RX(pi/2) 0
RZ(0.9775965506226627) 0
RX(-pi/2) 0
RZ(-2.92074085228763) 0
MEASURE 0 ro[0]
HALT                                    # Exiting rewiring: #(0 1 2)
NIL
```
