### ISSUE TITLE
Make OPERATOR-MATCH less verbose

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quilc#30]
e.g. in 
```
(defun CNOT-to-native-CNOTs (chip-spec cnot-gate)
  (operator-match
    (((("CNOT" () q0 q1) cnot-gate))
     ;; ...
     )
    (_
     (give-up-compilation))))
```
IMO writing the above is difficult to do successfully on the first or second try.

**Comment by ecpeterson** [comment]
`operator-match` is dead, and its replacement is mildly better in this regard. I'm gonna close.
