### ISSUE TITLE
Fix the numerous reversals of qubit orderings for cliffords and paulis

### ISSUE THREAD

**Issue by AShiTheCoder** [rigetti/quilc#309]
After qubit orderings for cliffords and paulis were changed to the computational basis ordering, issues related to inconsistent qubit ordering conventions have repeatedly bitten us in the booty. All clifford and pauli related functions are now consistent in taking arguments in this ordering, but there are still many stray `reverse`s lying around, which should be cleaned up and restructured appropriately to reflect the logic of computational basis ordering.

**Comment by appleby** [comment]
Was this closed by #307, or is there still more to do?
