### ISSUE TITLE
pi/2 is pretty printed but not 2*pi

### ISSUE THREAD

**Issue by appleby** [rigetti/quilc#314]
Is there some reason to not pretty-print integer multiples of pi?  If not, fix it.

This originally came up in a code review here https://github.com/rigetti/quilc/pull/257#discussion_r288606203, where it was suggested that `*print-fractional-radians*` would be a good place to start investigating this.

**Comment by ecpeterson** [comment]
Based on https://github.com/rigetti/quilc/blob/911c76ed5348d86decccee98fc1369c6d0e37985/src/ast.lisp#L1054 , it seems like we also don't print out e.g. 3/2 * pi, which might also be nice. Go as wild with this as you like.

**Comment by appleby** [comment]
> Based on
> 
> https://github.com/rigetti/quilc/blob/911c76ed5348d86decccee98fc1369c6d0e37985/src/ast.lisp#L1054
> 
> , it seems like we also don't print out e.g. 3/2 * pi, which might also be nice. Go as wild with this as you like.

I just happend to come across this exact expression while working on #273 and, weirdly, it seems both `3/2*pi` and `3*pi/2` are pretty-printed, but not `3*pi`.  Haven't looked at the code yet. Maybe it requires a fraction in order to kick in...

```lisp
CL-USER> (quil::print-parsed-program (quil:parse-quil "RX(3*pi/2) 0"))
RX(3*pi/2) 0
NIL
CL-USER> (quil::print-parsed-program (quil:parse-quil "RX(3/2*pi) 0"))
RX(3*pi/2) 0
NIL
CL-USER> (quil::print-parsed-program (quil:parse-quil "RX(3*pi) 0"))
RX(9.42477796076938) 0
NIL
```

**Comment by appleby** [comment]
Just took a peek at `format-real`. It's clear that integer multiples (other than +/-1) are not checked. To be fair, the special variable is called `*print-fractional-radians*`, though I guess you could consider n*pi to have an implicit 1 in the denominator and call it a fraction.

I could try to twiddle the [fraction-detecting loop on line 1061](https://github.com/rigetti/quilc/blob/911c76ed5348d86decccee98fc1369c6d0e37985/src/ast.lisp#L1054) by prepending 1 to the list of `denom`s that get tried (and increasing the range of `numer` accordingly), but I think special-casing integer multiples with a `(floor r pi)` check prior to that loop is simpler.

**Comment by appleby** [comment]
It seems my brilliant idea to use `floor` to check for integer multiples has a minor complication for certain numbers of the form 2^n * x * pi.  For example, for x = 11:

```
CL-USER> (floor (* 11 pi) pi)
10
3.1415926535897896d0
CL-USER> (floor (* 22 pi) pi)
21
3.1415926535897825d0
```

:confused: Guess, it's time to (re-)read [What Every Computer Scientist Should Know About Floating-Point Arithmetic](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)...

This can be worked around, but is enough to make me reconsider an approach similar to the existing fraction-detecting loop, but just checking small integer multiples, instead.
