### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by plewandowska777** [rigetti/quilc#325]
When building for source I get the following error: 
```
 fatal error: tweedledum/gates/gate_set.hpp: No such file or directory
 #include <tweedledum/gates/gate_set.hpp>
```
Steps to retroduce: 
```
git clone https://github.com/rigetti/quilc.git 
cd quilc 
git checkout v1.9.1
make
```

**Comment by appleby** [comment]
You need to `git submodule update --init` after `git clone`.

I will make a note to add this to the README. Thanks for reporting!
