### ISSUE TITLE
Fidelity estimates exceeding 100% crash quilc

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#378]
The fidelity estimates stored in Forest DB (e.g., Aspen-4's qubit 17's f1QRB at the time of this writing) can exceed 100%. This causes quilc to crash.

An easy fix for this is to clamp interpreted fidelities to `+near-perfect-fidelity+`. It is probably better to understand why these values appear at all before proceeding.

**Comment by appleby** [comment]
Note to self: I left a handful of TODOs in the diff for #380 related to this issue. Remember to clean those up once this issue is addressed.
