### ISSUE TITLE
[lexer, parser] Introduce ; as a faux newline

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#386]
It's getting annoying seeing `(format nil "X 1~%X 2~%X 3")`. It's also annoying to not be able to write valid snippets of Quil on one line.

I propose introducing `<X>\s*;\s*<Y>` to mean `<X>` is its own line (with particular indentation), and `Y` is its own line with indentation inherited from `<X>`.

Tricky parts of implementing this: Tracking source locations, getting indentation right, etc.

What is *NOT* needed is a printer that reproduces `;`. Newlines can just be put in there.

**Comment by kilimanjaro** [comment]
Got it ; Done

**Comment by stylewarning** [comment]
@kilimanjaro Can you add a pyQuil issue too? And a rigetti/quil issue to update the spec?
