### ISSUE TITLE
Cannot build quilc

### ISSUE THREAD

**Issue by doctor-entropy** [rigetti/quilc#397]
Hello! I am getting this error when I try to 'make quilc'. Please help! Thanks!
![Screenshot from 2019-08-29 19-57-42](https://user-images.githubusercontent.com/36320811/63988195-3be1bc00-ca98-11e9-9862-555aa1ed04bd.png)

**Comment by appleby** [comment]
Hi! Thanks for reporting.

The backtrace appears to be truncated in that screenshot... can you copy/paste the full text into a comment please?

**Comment by appleby** [comment]
Also, what version of SBCL are you using?

**Comment by doctor-entropy** [comment]
Here you go. 

`sbcl --noinform --no-userinit --no-sysinit --non-interactive --load /home/zeus/quicklisp/setup.lisp --eval '(push (truename ".") asdf:*central-registry*)' --eval '(push :drakma-no-ssl *features*)' --eval "(push (truename \"../\") ql:*local-project-directories*)" \
	 \
	--eval '(ql:quickload "quilc")' \
	--eval '(ql:write-asdf-manifest-file "system-index.txt")'
To load "quilc":
  Load 1 ASDF system:
    quilc
; Loading "quilc"
.......; pkg-config libffi --cflags
; ERROR: Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {100354D2B3}>
 with command ("pkg-config" "libffi" "--cflags")
 exited with error code 1

Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found

; Attempting to continue anyway.
; cc -o /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel-tmpGHU3ALSV.o -c -g -Wall -Wundef -Wsign-compare -Wpointer-arith -O3 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wunused-parameter -fno-omit-frame-pointer -momit-leaf-frame-pointer -fno-pie -fPIC -I/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/ /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.c
/home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.c:7:10: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
          ^~~~~~~
compilation terminated.
Unhandled CFFI-GROVEL:GROVEL-ERROR in thread #<error printing a SB-THREAD:THREAD: #<PRINT-NOT-READABLE {10035BEDE3}>>: Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {10035BB123}>
 with command ("cc" "-o" "/home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel-tmpGHU3ALSV.o" "-c" "-g" "-Wall" "-Wundef" "-Wsign-compare" "-Wpointer-arith" "-O3" "-D_LARGEFILE_SOURCE" "-D_LARGEFILE64_SOURCE" "-D_FILE_OFFSET_BITS=64" "-Wunused-parameter" "-fno-omit-frame-pointer" "-momit-leaf-frame-pointer" "-fno-pie" "-fPIC" "-I/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/" "/home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.c")
 exited with error code 1

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10004F04C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<CFFI-GROVEL:GROVEL-ERROR "~a" {10035BD4B3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<CFFI-GROVEL:GROVEL-ERROR "~a" {10035BD4B3}>)
2: (INVOKE-DEBUGGER #<CFFI-GROVEL:GROVEL-ERROR "~a" {10035BD4B3}>)
3: (ERROR CFFI-GROVEL:GROVEL-ERROR :FORMAT-CONTROL "~a" :FORMAT-ARGUMENTS (#<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10035BCD83}>))
4: (CFFI-GROVEL:GROVEL-ERROR "~a" #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10035BCD83}>)
5: ((FLET "THUNK" :IN CFFI-GROVEL:PROCESS-GROVEL-FILE))
6: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (FLET "THUNK" :IN CFFI-GROVEL:PROCESS-GROVEL-FILE) {7F2CA54765FB}>)
7: (CFFI-GROVEL:PROCESS-GROVEL-FILE #P"/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types.lisp" #P"/home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types.processed-grovel-file")
8: ((:METHOD ASDF/ACTION:PERFORM (CFFI-GROVEL::PROCESS-OP CFFI-GROVEL:GROVEL-FILE)) #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "cffi-libffi" "libffi" "libffi-types">) [fast-method]
9: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "cffi-libffi" "libffi" "libffi-types">)
10: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
11: ((:METHOD ASDF/ACTION:PERFORM :AROUND (CFFI-GROVEL::PROCESS-OP CFFI-GROVEL::CC-FLAGS-MIXIN)) #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "cffi-libffi" "libffi" "libffi-types">) [fast-method]
12: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<CFFI-GROVEL::PROCESS-OP > #<CFFI-GROVEL:GROVEL-FILE "cffi-libffi" "libffi" "libffi-types">) [fast-method]
13: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002FA1FA3}>) [fast-method]
14: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
15: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002FA1FA3}>) [fast-method]
16: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "quilc"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
17: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "quilc"> :VERBOSE NIL)
18: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
19: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "quilc"> :VERBOSE NIL) [fast-method]
20: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "quilc" :VERBOSE NIL)
21: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
22: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "quilc" :VERBOSE NIL) [fast-method]
23: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002F9DADB}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
24: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
25: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002F9149B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
26: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "quilc" :VERBOSE NIL) [fast-method]
27: (ASDF/OPERATE:LOAD-SYSTEM "quilc" :VERBOSE NIL)
28: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1002F9122B}>)
29: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "quilc" :PROMPT NIL)
30: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002C0358B}>) [fast-method]
31: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1002464563}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002C0358B}>) [fast-method]
32: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) "quilc" :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
33: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002BF073B}>)
34: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD "quilc") #<NULL-LEXENV>)
35: (EVAL (QUICKLISP-CLIENT:QUICKLOAD "quilc"))
36: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "/home/zeus/quicklisp/setup.lisp") (:EVAL . "(push (truename \".\") asdf:*central-registry*)") (:EVAL . "(push :drakma-no-ssl *features*)") (:EVAL . "(push (truename \"../\") ql:*local-project-directories*)") (:EVAL . "(ql:quickload \"quilc\")") (:EVAL . "(ql:write-asdf-manifest-file \"system-index.txt\")") (:QUIT)))
37: (SB-IMPL::TOPLEVEL-INIT)
38: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
39: ((FLET "WITHOUT-INTERRUPTS-BODY-7" :IN SAVE-LISP-AND-DIE))
40: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
make: *** [Makefile:31: system-index.txt] Error 1
`

I am using SBCL 1.5.6

And thank you!

**Comment by appleby** [comment]
It looks like cffi is failing to find libffi headers.  What operating system are you running?  Do you have libffi installed? If you're running linux, what does `locate libffi.h` say? If that doesn't work, try `ldconfig -p | grep libffi`.

Also note there is [an open QVM issue](https://github.com/rigetti/qvm/issues/168) related to a compile failure with SBCL 1.5.6.  I don't think the backtrace you posted indicates the same issue, but something to be aware of.

**Comment by doctor-entropy** [comment]
Here you go. The first command didn't output anything.

`libffi.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libffi.so.6`
`libffi.so.6 (libc6) => /usr/lib/i386-linux-gnu/libffi.so.6`

**Comment by doctor-entropy** [comment]
Also, I am running this on Ubuntu 18.10

**Comment by appleby** [comment]
Sorry, typo on my part. The header file is actually `ffi.h` not `libffi.h`.

Do you have the package [`libffi-dev`](https://packages.ubuntu.com/cosmic/libffi-dev) installed?

Try `locate ffi.h`  and also `apt list --installed | grep libffi`.

**Comment by appleby** [comment]
If you don't see `libffi-dev` in the output of that last command, please try following these steps to install libffi-dev and BLAS / LAPACK:

https://github.com/rigetti/magicl/blob/master/doc/requirements.md

**Comment by doctor-entropy** [comment]
Hey there, I installed libffi-dev and I tried to make quilc, But now I am getting a Corruption warning.

Here is the backtrace,

sbcl --noinform --no-userinit --no-sysinit --non-interactive --load /home/zeus/quicklisp/setup.lisp --eval '(push (truename ".") asdf:*central-registry*)' --eval '(push :drakma-no-ssl *features*)' --eval "(push (truename \"../\") ql:*local-project-directories*)" \
	 \
	--eval '(ql:quickload "quilc")' \
	--eval '(ql:write-asdf-manifest-file "system-index.txt")'
To load "quilc":
  Load 1 ASDF system:
    quilc
; Loading "quilc"
.......; pkg-config libffi --cflags

; cc -o /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel-tmpGHU3ALSV.o -c -g -Wall -Wundef -Wsign-compare -Wpointer-arith -O3 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wunused-parameter -fno-omit-frame-pointer -momit-leaf-frame-pointer -fno-pie -fPIC -I/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/ /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.c
/home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.c: In function ‘main’:
/home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.c:12:7: warning: unused variable ‘autotype_tmp’ [-Wunused-variable]
   int autotype_tmp;
       ^~~~~~~~~~~~
; cc -o /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel-tmpAAURSO1 -g -Wl,--export-dynamic -no-pie /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.o
; /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/quicklisp/dists/quicklisp/software/cffi_0.20.1/libffi/libffi-types__grovel.grovel-tmp.lisp
...........................................
[package magicl.foreign-libraries]................
[package magicl.cffi-types].......................
[package magicl.blas-cffi]........................
[package magicl.lapack-cffi]......................
[package magicl.expokit-cffi].....................
[package magicl]..................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
[package org.tfeb.hax.abstract-classes]...........
[package cl-quil.resource]........................
[package cl-quil].................................
[package cl-quil.clifford]........................
..................................................
..................................................
..................................................
..................................................
[package cl-quil-benchmarking]....................
[package quilc].......
sbcl --noinform --no-userinit --no-sysinit --non-interactive  \
        --eval "(setf sb-ext:\*on-package-variance\* '(:warn (:swank :swank-backend :swank-repl) :error t))" \
	--eval '(push :drakma-no-ssl *features*)' \
	--load "build-app.lisp" \
	 \
	
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/cl-ppcre-20190521-git/cl-ppcre.asd" contains definition for system "cl-ppcre-test". Please only define "cl-ppcre" and secondary systems with a name starting with "cl-ppcre/" (e.g. "cl-ppcre/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/parse-float-20171019-git/parse-float.asd" contains definition for system "parse-float-tests". Please only define "parse-float" and secondary systems with a name starting with "parse-float/" (e.g. "parse-float/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/cl-fad-20190813-git/cl-fad.asd" contains definition for system "cl-fad-test". Please only define "cl-fad" and secondary systems with a name starting with "cl-fad/" (e.g. "cl-fad/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/pzmq-20190710-git/pzmq.asd" contains definition for system "pzmq-compat". Please only define "pzmq" and secondary systems with a name starting with "pzmq/" (e.g. "pzmq/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/pzmq-20190710-git/pzmq.asd" contains definition for system "pzmq-test". Please only define "pzmq" and secondary systems with a name starting with "pzmq/" (e.g. "pzmq/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/pzmq-20190710-git/pzmq.asd" contains definition for system "pzmq-examples". Please only define "pzmq" and secondary systems with a name starting with "pzmq/" (e.g. "pzmq/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/flexi-streams-20190107-git/flexi-streams.asd" contains definition for system "flexi-streams-test". Please only define "flexi-streams" and secondary systems with a name starting with "flexi-streams/" (e.g. "flexi-streams/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/trivial-utf-8-20111001-darcs/trivial-utf-8.asd" contains definition for system "trivial-utf-8-tests". Please only define "trivial-utf-8" and secondary systems with a name starting with "trivial-utf-8/" (e.g. "trivial-utf-8/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/puri-20180228-git/puri.asd" contains definition for system "puri-tests". Please only define "puri" and secondary systems with a name starting with "puri/" (e.g. "puri/test") in that file.
WARNING: System definition file #P"/home/zeus/quicklisp/dists/quicklisp/software/cl-base64-20150923-git/cl-base64.asd" contains definition for system "cl-base64-tests". Please only define "cl-base64" and secondary systems with a name starting with "cl-base64/" (e.g. "cl-base64/test") in that file.
WARNING: redefining CL-QUIL::LEXICAL-CONTEXT in DEFGENERIC
WARNING: redefining TRIVIAL-BENCHMARK:RUNNING in DEFGENERIC
WARNING: redefining TRIVIAL-BENCHMARK:METRICS in DEFGENERIC
WARNING: redefining TRIVIAL-BENCHMARK:STARTING-VALUE in DEFGENERIC
In file included from /home/zeus/Documents/quil/quilc/src/contrib/tweedledum/tweedledum/include/tweedledum/algorithms/synthesis/dbs.hpp:18,
                 from /home/zeus/Documents/quil/quilc/src/contrib/tweedledum/tweedledum.c:8:
/home/zeus/Documents/quil/quilc/src/contrib/tweedledum/tweedledum/libs/kitty/kitty/esop.hpp:36:2: warning: #warning "DEPRECATED: the functions in this file are marked as deprecated.  Most recent implementation can be found in https://github.com/hriener/easy/ in the file src/esop/constructors.hpp" [-Wcpp]
 #warning "DEPRECATED: the functions in this file are marked as deprecated.  Most recent implementation can be found in https://github.com/hriener/easy/ in the file src/esop/constructors.hpp"
  ^~~~~~~
; compiling file "/home/zeus/Documents/quil/quilc/src/contrib/tweedledum/tweedledum.lisp" (written 29 AUG 2019 07:40:16 PM):
; compiling (DEFPACKAGE #:CL-QUIL.TWEEDLEDUM ...)
; compiling (IN-PACKAGE #:CL-QUIL.TWEEDLEDUM)
; compiling (DEFINE-FOREIGN-LIBRARY (LIBTWEEDLEDUM :SEARCH-PATH ...) ...)
; compiling (DEFVAR *TWEEDLEDUM-LIBS-LOADED* ...)
; compiling (DEFCFUN (%SYNTHESIS-DBS "tweedledum_synthesis_dbs") ...)
; compiling (DEFUN SYNTHESIS-DBS ...)
; compiling (DEFUN COMPILE-PERM-GATE-WITH-TWEEDLEDUM ...)
; compiling (DEFUN LOAD-TWEEDLEDUM ...)
; compiling (DEFUN RUN-TWEEDLEDUM-TESTS ...)

; wrote /home/zeus/.cache/common-lisp/sbcl-1.5.6-linux-x64/home/zeus/Documents/quil/quilc/src/contrib/tweedledum/tweedledum-tmpGHU3ALSV.fasl
; compilation finished in 0:00:00.028
Zapping info...
CORRUPTION WARNING in SBCL pid 16895(tid 0x7f6092394b80):
Memory fault at (nil) (pc=0x100001a697, fp=0x7f6091b6eaf8, sp=0x7f6091b6eaf0) tid 0x7f6092394b80
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
While evaluating the form starting at line 13, column 0
  of #P"/home/zeus/Documents/quil/quilc/build-app.lisp":
Unhandled SB-SYS:MEMORY-FAULT-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                 {10004F04C3}>:
CORRUPTION WARNING in SBCL pid 16895(tid 0x7f6092394b80):
Memory fault at (nil) (pc=0x100001f917, fp=0x7f6091b6d970, sp=0x7f6091b6d968) tid 0x7f6092394b80
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
  #<error printing a SB-SYS:MEMORY-FAULT-ERROR: #<SB-SYS:MEMORY-FAULT-ERROR {100667F793}>>

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10004F04C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-SYS:MEMORY-FAULT-ERROR {100667AB33}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-SYS:MEMORY-FAULT-ERROR {100667AB33}>)
2: (INVOKE-DEBUGGER #<SB-SYS:MEMORY-FAULT-ERROR {100667AB33}>)
3: (ERROR SB-SYS:MEMORY-FAULT-ERROR :ADDRESS 0)
4: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000000))
5: ("foreign function: call_into_lisp")
6: ("foreign function: funcall2")
7: ("foreign function: handle_memory_fault_emulation_trap")
8: ("foreign function: handle_trap")
9: ("foreign function: #x418BFE")
unhandled condition in --disable-debugger mode, quitting
CORRUPTION WARNING in SBCL pid 16895(tid 0x7f6092394b80):
Memory fault at (nil) (pc=0x1000018027, fp=0x7f6091b6df00, sp=0x7f6091b6def8) tid 0x7f6092394b80
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
make: *** [Makefile:79: quilc] Error 1

**Comment by appleby** [comment]
This latest failure looks to be similar to the [QVM issue](https://github.com/rigetti/qvm/issues/168) I mentioned previously.

For now, I recommend downgrading to SBCL 1.5.5 if you can.  Alternatively, you can wait until https://github.com/rigetti/quilc/pull/402 is merged, but there are still unresolved bugs that need investigation there, so it's not certain when that will be ready to merge.

**Comment by doctor-entropy** [comment]
Downgrading to SBCL 1.5.5 worked for me. Thank you for your help! :)
