### ISSUE TITLE
Launching quilc -S in powershell crash

### ISSUE THREAD

**Issue by rumschuettel** [rigetti/quilc#429]
Hi!

Latest quilc version `1.11.1 [c914232]` crashes when launched as `quilc -S` in powershell; this is the error message:

```
+-----------------+
|  W E L C O M E  |
|   T O   T H E   |
|  R I G E T T I  |
|     Q U I L     |
| C O M P I L E R |
+-----------------+
Copyright (c) 2016-2019 Rigetti Computing.

This is a part of the Forest SDK. By using this program
you agree to the End User License Agreement (EULA) supplied
with this program. If you did not receive the EULA, please
contact <support@rigetti.com>.

! ! ! Error: Malformed input for RFC 5424 syslog message. The violated assertion was
(CL-SYSLOG::VALID-APP-NAME-P CL-SYSLOG::APP-NAME)
```
It works in the standard `cmd`.

Best,
Johannes

**Comment by rumschuettel** [comment]
I invoke it literally as written, i.e. `quilc -S`.

appleby <notifications@github.com> schrieb am Do., 19. Sep. 2019, 19:48:

**Comment by notmgsk** [comment]
This is fixed in the latest release, which can be found at https://qcs.rigetti.com/sdk-downloads
