### ISSUE TITLE
Calculate 'expected durations' at runtime

### ISSUE THREAD

**Issue by ecpeterson** [rigetti/quilc#439]
quilc makes assertions about the expected runtimes of `SWAP` and of a generic 2Q interaction. Now that it's possible to configure the duration of native gates at runtime, these values should be dynamically calculated based off of that.

**Comment by kilimanjaro** [comment]
cf. `"time-bound"` on `hardware-obj-misc-data`, which is currently set manually in `chip-specification.lisp`

**Comment by ecpeterson** [comment]
Closed in #395.
