### ISSUE TITLE
Improve the default chip-building functionality

### ISSUE THREAD

**Issue by kilimanjaro** [rigetti/quilc#448]
There are two ways to construct a chip specification. The general case is through the machinery of `chip-reader.lisp`, which takes an ISA description in JSON format. There are also some helpful routines in `chip-specification.lisp`, which are used to construct some of the basic/default chip architectures (e.g. everything involved in `build-nq-linear-chip`). 

These latter routines are alluring but do not work robustly, For example, if one wanted a linear chip supporting both `CZ` and `SWAP` operations natively, adding the line
```
(install-link-onto-chip chip-spec i (1+ i) :architecture ':SWAP)
```
in the appropriate place in `build-nq-linear-chip` would _not_ work (one will see a later failure in `find-shortest-compiler-path`). 

Here I would request some general improvements in this area, allowing for easy procedural construction of chips without recourse to the JSON middleman.

**Comment by notmgsk** [comment]
Doesn't `(build-nq-linear-chip n :architecture '(:CZ :SWAP))` achieve that?

**Comment by kilimanjaro** [comment]
Yes, I was misusing `install-link-onto-chip`

**Comment by notmgsk** [comment]
Can we close this, or is there still something to be done?
