### ISSUE TITLE
XY vs PISWAP

### ISSUE THREAD

**Issue by kilimanjaro** [rigetti/quilc#454]
We currently have the following standard gate definition in `stdgates.quil`:

```
DEFGATE PISWAP(%theta):
    1, 0,               0,               0
    0, cos(%theta/2),   i*sin(%theta/2), 0
    0, i*sin(%theta/2), cos(%theta/2),   0
    0, 0,               0,               1
```

This is the same as XY_{-\theta}, where the family XY is defined in https://arxiv.org/abs/1904.10541, the only difference being the direction of parameterization:

```
DEFGATE XY(%theta):
    1,  0,               0,               0
    0, cos(%theta/2),   -i*sin(%theta/2), 0
    0, -i*sin(%theta/2), cos(%theta/2),   0
    0,  0,               0,               1
```

It would make sense to include this definition of `XY` in `stdgates.quil`, possibly replacing `PISWAP`. We should also make sure that the parameterization is the standard one.

**Comment by ecpeterson** [comment]
The discrepancy in parametrization ultimately stems from a typo in an internal note from 2017 + me not knowing what the standard choices of Pauli matrices is, & the discrepancy in notation stems from me not knowing that everyone else calls this thing "XY". I'm in strong favor of eliminating PISWAP and replacing it with XY.

I don't think we should spend much time hand-wringing about the change: this functionality has been around for a while, but there's been little user adoption.

**Comment by stylewarning** [comment]
`🥧SWAP`

**Comment by ecpeterson** [comment]
We've apparently decided to embrace the typo. The weird sign (and, with it, the definition of PISWAP) is here to stay.

**Comment by stylewarning** [comment]
Re-opening just to ask some more questions and maybe make Action Items (TM).

1. Should we `DEFCIRCUIT XY` as `PISWAP` in stdgates.quil? Or the other way round?
2. Should we update the comment in stdgates.quil with more information (e.g., the "True" definition of XY vs what we have)?

**Comment by ecpeterson** [comment]
1. The compiler has long had a bunch of routines for rewriting PISWAPs; we recently "imported" these for XY by writing PISWAP -> XY and XY -> PISWAP translators and letting the crawler figure the rest out. I worry that by making either of these secretly a circuit application, we'll lose the ability to do this.
2. No opinion. I'd feel more strongly if there were a growing crowd of physicists saying we messed this sign up, but even the physicists are picking the 'wrong' sign, and so I'm starting to feel that it's only 'wrong' in my own head.
