### ISSUE TITLE
distinguish between different kinds of compiler give-ups

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#46]
e.g.:

* compiler-invalid-domain
* compiler-acts-trivially
* compiler-rewrite-does-not-apply
 etc.

Any more?

**Comment by stylewarning** [comment]
A few different classes have been added, see e.g. here: https://github.com/rigetti/quilc/blob/master/src/compilation-methods.lisp#L29

This issue would be going through current calls to `give-up-compilation` and marking them appropriately, as well as adding a new condition like `compiler-rewrite-does-not-apply`.

**Comment by matt-y** [comment]
I'd like to take this! Thanks.
