### ISSUE TITLE
Support controlled parametric gates

### ISSUE THREAD

**Issue by jlapeyre** [rigetti/quilc#476]
It would be useful to add support for at least some controlled parametric gates. For example compiling
```
DECLARE theta REAL[1]
CONTROLLED RY(theta[0]) 1 0
```
fails with the error `Condition CL-QUIL::UNKNOWN-GATE-PARAMETER`. The function [`gate-matrix`](https://github.com/rigetti/quilc/blob/a64cb07b52db16e1b78ff66f5bd630b901947493/src/gates.lisp#L37) first checks that all elements of the matrix are numerical values, which they are not.

The same error is thrown with the following program which writes `RY` explicitly
```
DEFGATE CRY(%theta):
    1, 0, 0, 0
    0, 1, 0, 0
    0, 0, COS(%theta/2), -1*SIN(%theta/2)
    0, 0, SIN(%theta/2), COS(%theta/2)

DECLARE theta REAL[1]
CRY(theta[0]) 1 2
```
A circuit equivalent to `CONTROLLED RY(theta[0]) q1 q2` that *can* be successfully compiled and applied is
```
RY(theta/2) q2
CNOT q1 q2
RY(-theta/2) q2
CNOT q1, q2
```

**Comment by ecpeterson** [comment]
Closed by #484.
