### ISSUE TITLE
Providing a wildcard to the "arguments" key of a qubit in an ISA leads to the compiler crawler missing appropriate compilation routines.

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quilc#567]
PyQuil will construct the following ISA for a `1q-qvm` device:
```
{
    "isa": {
        "1Q": {
            "0": {
                "gates": [
                    {
                        "operator": "I",
                        "parameters": [],
                        "arguments": [
                            "_"
                        ],
                        "fidelity": null,
                        "duration": null
                    },
                    {
                        "operator": "RX",
                        "parameters": [
                            0.0
                        ],
                        "arguments": [
                            "_"
                        ],
                        "fidelity": null,
                        "duration": null
                    },
                    {
                        "operator": "RX",
                        "parameters": [
                            1.5707963267948966
                        ],
                        "arguments": [
                            "_"
                        ],
                        "fidelity": null,
                        "duration": null
                    },
                    {
                        "operator": "RX",
                        "parameters": [
                            -1.5707963267948966
                        ],
                        "arguments": [
                            "_"
                        ],
                        "fidelity": null,
                        "duration": null
                    },
                    {
                        "operator": "RX",
                        "parameters": [
                            3.141592653589793
                        ],
                        "arguments": [
                            "_"
                        ],
                        "fidelity": null,
                        "duration": null
                    },
                    {
                        "operator": "RX",
                        "parameters": [
                            -3.141592653589793
                        ],
                        "arguments": [
                            "_"
                        ],
                        "fidelity": null,
                        "duration": null
                    },
                    {
                        "operator": "RZ",
                        "parameters": [
                            "theta"
                        ],
                        "arguments": [
                            "_"
                        ],
                        "fidelity": null,
                        "duration": null
                    },
                    {
                        "operator": "MEASURE",
                        "qubit": "_",
                        "target": "_",
                        "duration": null,
                        "fidelity": null
                    },
                    {
                        "operator": "MEASURE",
                        "qubit": "_",
                        "target": null,
                        "duration": null,
                        "fidelity": null
                    }
                ]
            }
        },
        "2Q": {
            
        }
    },
    "specs": {
        "1Q": {
            "0": {
                "f1QRB": 0.909,
                "f1QRB_std_err": 0.01,
                "f1Q_simultaneous_RB": 0.909,
                "f1Q_simultaneous_RB_std_err": 0.02,
                "fRO": 0.9,
                "T1": 3e-05,
                "T2": 3e-05,
                "fActiveReset": 0.909
            },
            "1": {
                "f1QRB": 0.909,
                "f1QRB_std_err": 0.01,
                "f1Q_simultaneous_RB": 0.909,
                "f1Q_simultaneous_RB_std_err": 0.02,
                "fRO": 0.9,
                "T1": 3e-05,
                "T2": 3e-05,
                "fActiveReset": 0.909
            }
        },
        "2Q": null
    }
}

```
This ought to read as: on qubit `0`, the gates `I`, `RX(+/- n pi)`, and `RX(theta)` are native. The compiler will use this information to construct a list of compilation routines that will move us toward the above native gateset (see `compute-applicable-compilers`) or keep us within the gateset but produce more optimal output (i.e. shorter gate sequences; see `compute-applicable-reducers`).

Given the above ISA, however, the compiler decides that the routine `agglutinate-RXs` is not appropriate. After some exploration, this is due to the wildcard in all of the `"arguments"` fields of the `"RX"` gates in the ISA. Changing the wildcard to be specific (i.e. in this case changing it to `0`) fixes the issue. Indeed, `(build-nq-fully-connected-chip 1)` produces an ISA whose `"arguments"` are specifically the qubit under which they are keyed.

There are a few options here:
* a. pyQuil is in error, and should not be providing wildcards under the arguments field
* b. quilc ought to "correct" the wildcard to the appropriate qubit
* c. quilc ought to use the wildcard, with some (possibly missing) logic to relax its constraints when picking applicable reducers/compilers

I'm not sure why the `"arguments"` key needs to exist at all. My understanding is that all gates listed under a particular qubit in the ISA (`"0"` above) apply to that qubit, so repeating that qubit index under `"arguments"` seems redundant. It's even less clear to me what a wildcard here could mean.

**Comment by notmgsk** [comment]
The above issue was spotted by @jlapeyre when compiling the following
```
QUIL> (let ((chip (read-chip-spec-file "~/bad.isa"))
            (progm (parse-quil "Z 0; Z 0")))
        (print-parsed-program
         (compiler-hook progm chip)))
RX(pi/2) 0                              # Entering rewiring: #(0)
RX(-pi/2) 0
HALT                                    # Exiting rewiring: #(0)
NIL
```
where `bad.isa` is the above.

**Comment by appleby** [comment]
I vote (a) unless we can think of reason (c) applies.  Maybe "arguments" is only supposed to be a wildcard if "operator" is as well?  See https://github.com/rigetti/quilc/pull/470

**Comment by appleby** [comment]
I take it back. It looks like the changes in #470 only enabled the "operator" field to be a wildcard, but wildcard "arguments" were already permitted.

**Comment by appleby** [comment]
> I'm not sure why the "arguments" key needs to exist at all. My understanding is that all gates listed under a particular qubit in the ISA ("0" above) apply to that qubit, so repeating that qubit index under "arguments" seems redundant. It's even less clear to me what a wildcard here could mean.

Did we ever figure out why wildcard arguments are needed? This seems like a relatively recent change to pyquil rigetti/pyquil#1151. Would it make sense to instead update pyquil's [`convert_gate_type_to_gate_information `](https://github.com/rigetti/pyquil/pull/1151/files#diff-196a119d3a2733dcd8c7cccb0bb2728bR194) to just include the concrete qubits in the arguments field, rather than a wildcard?

**Comment by appleby** [comment]
I guess on the other hand, pyquil 2.16 is already released with these changes, so maybe it needs to be fixed in quilc in any case.

**Comment by notmgsk** [comment]
> > I'm not sure why the "arguments" key needs to exist at all. My understanding is that all gates listed under a particular qubit in the ISA ("0" above) apply to that qubit, so repeating that qubit index under "arguments" seems redundant. It's even less clear to me what a wildcard here could mean.
> 
> Did we ever figure out why wildcard arguments are needed? This seems like a relatively recent change to pyquil [rigetti/pyquil#1151](https://github.com/rigetti/pyquil/pull/1151). Would it make sense to instead update pyquil's [`convert_gate_type_to_gate_information `](https://github.com/rigetti/pyquil/pull/1151/files#diff-196a119d3a2733dcd8c7cccb0bb2728bR194) to just include the concrete qubits in the arguments field, rather than a wildcard?

Sorry for missing this.

Wildcards are needed in the case of multi-qubit gates. 

For example, you might like to specify that `CZ 0 1` is native and `CZ 1 0` is *not* native. You would achieve this by specifying something like
```
...
      "0-1": {
        "gates": [
          {
            "operator": "CZ",
            "parameters": [],
            "arguments": [
              "0",
              "1"
            ],
            "fidelity": 0.978778452404334,
            "duration": 200
          },
        ]
      }
...
```
For brevity's sake, if you want both `CZ 0 1` and `CZ 1 0` to be native then you would use a wildcard under the arguments field.

**Comment by appleby** [comment]
makes sense. thanks for clarifying.
