### ISSUE TITLE
Modifiers are applied everywhere a circuit pops up

### ISSUE THREAD

**Issue by jmbr** [rigetti/quilc#586]
The following example,
```lisp
(loop :with program := (parse-quil "
DEFCIRCUIT FOOBAR:
    X 0

FOOBAR
DAGGER FOOBAR
")
      :for i :across (parsed-program-executable-code program) :do
        (print-instruction i)
        (terpri))
```
prints
```
DAGGER X 0
DAGGER X 0
```
Meaning that the DAGGER modifier was applied to each instance of the circuit rather than just the second one. The same happens with the CONTROLLED modifier.

**Comment by stylewarning** [comment]
Onlookers should start here: https://github.com/rigetti/quilc/blob/master/src/analysis/expansion.lisp
