### ISSUE TITLE
Allow quilc to be compiled to a dynamic library

### ISSUE THREAD

**Issue by stylewarning** [rigetti/quilc#63]
This is possible with Embeddable Common Lisp and I think would be the most straightforward way to do it instead of trying to coax SBCL into doing it.

quilc isn't all portable to ECL, so this issue would require stubbing out the appropriate ECL functionality.

The biggest trouble, however, is that arrays of `(complex double-float)` must be supported by MAGICL. ECL doesn't support it yet, and would be critical to getting this to work. See [this thread](https://gitlab.com/embeddable-common-lisp/ecl/issues/459) on the ECL issue tracker.

**Comment by jmbr** [comment]
I've been going through some of the documentation of SBCL's internals recently and it seems like this might be viable using so-called "alien callbacks" and libsbcl.so
