### ISSUE TITLE
Libzmq3-dev was not installed automatically

### ISSUE THREAD

**Issue by AlreadyTakenJonas** [rigetti/quilc#633]
I installed the forest sdk from https://qcs.rigetti.com/sdk-downloads and run the .deb.run. No errors while installing. Executing quilc throws the error: 

Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006804F3}>:
  Error opening shared object "libzmq.so":
  libzmq.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006804F3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E3D763}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E3D763}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E3D763}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." "libzmq.so" "libzmq.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden")
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libzmq.so" :NAMESTRING "libzmq.so" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libzmq.so" :NAMESTRING "libzmq.so" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT)
9: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
11: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

Manually installing libzmq3-dev solved the issue. I'm running Ubuntu 18.04.4 LTS.

**Comment by notmgsk** [comment]
@AlreadyTakenJonas Which of the packages did you install? There are three: deb, rpm, and barebones.

**Comment by AlreadyTakenJonas** [comment]
I installed the .deb.

**Comment by notmgsk** [comment]
@AlreadyTakenJonas Apologies for the delay. Think I've fixed this. Can you try with: http://downloads.rigetti.com/qcs-sdk/forest-sdk-2.19.1-linux-deb.tar.bz2

**Comment by notmgsk** [comment]
I'm going to close this. In my own testing it is resolved. Please reopen if you disagree.

**Comment by AlreadyTakenJonas** [comment]
Works fine on my system as well. Tanks for fixing it.
