### ISSUE TITLE
Quilc does not agglutinate RXs when using pyQuil

### ISSUE THREAD

**Issue by msohaibalam** [rigetti/quilc#640]
If I run `echo 'RX(-pi/2) 0; RX(pi/2) 0' | ./quilc` in a terminal, I get what I expect, i.e. the two RXs compile to just the identity
```
HALT                                    # Entering/exiting rewiring: (#(0 1 2 3 4 5 6 7) . #(0 1 2 3 4 5 6 7))
```

However, if I run the same code inside a python session, the two instructions don't collapse into the identity.
```
from pyquil import get_qc, Program
from pyquil.gates import RX
import numpy as np

qc = get_qc('2q-qvm')
prog = Program(RX(-np.pi/2, 0), RX(np.pi/2, 0))
n_prog = qc.compiler.quil_to_native_quil(prog)
print(n_prog)
>>> RX(-pi/2) 0
>>> RX(pi/2) 0
>>> HALT
```

Why is this so?

**Comment by notmgsk** [comment]
Good spot. Looks like there is some info missing from the ISA. It works as expected if you use Aspen-type ISAs:
```
from pyquil import get_qc, Program

qc = get_qc("Aspen-4-2Q-C-qvm")
p = Program("""RX(-pi) 0
RX(pi) 0""")

print(qc.compile(p).program)

HALT
```

**Comment by stylewarning** [comment]
The quilc entrypoint is here: https://github.com/rigetti/quilc/blob/master/app/src/rpc-server.lisp#L50

I wonder what it's sending as a chip specification, and if we are hærkening back to the old issue of pattern matching.
