### ISSUE TITLE
Parametric compilation broken

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quilc#667]
For some qubits on Aspen-8 the following program raises a `compiler-does-not-apply` error.

```
import pyquil
qc = pyquil.get_qc('Aspen-8', as_qvm=True)
qc.compile(pyquil.Program("""DECLARE t REAL
RX(((1.0)*t[0])) 3"""))
```

```
RPCError: Unhandled error in host program:
Condition CL-QUIL::COMPILER-DOES-NOT-APPLY was signalled.
```

@colescott

**Comment by stylewarning** [comment]
Was the "broken after" determined by bisection?

**Comment by notmgsk** [comment]
Yes

**Comment by notmgsk** [comment]
Possibly a red herring, however. I have a different program that causes the issue before #655.

**Comment by stylewarning** [comment]
@notmgsk can you confirm your test case is fixed?

**Comment by notmgsk** [comment]
Confirmado
