### ISSUE TITLE
Slack status unclear

### ISSUE THREAD

**Issue by lukego** [rigetti/quilc#671]
README seems to suggest that the Slack `#dev` channel is available to hang out in, but if you try to join it seems to only accept people with an `@rigetti.com` or `@qxbranch.com` email address.

**Comment by notmgsk** [comment]
Huh. That shouldn't be the case, and I don't see anything in the settings that suggests this is the case. Can you post a screenshot of what you're seeing?

**Comment by stylewarning** [comment]
@lukego Maybe former and present devs now speak in `#qlisp` on Freenode. We ought to update the README.
